var myPlaylist = [
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4b1BYZlpOZExvRzQ',
		oga:'#',
		title:'1 thuở yêu người',
		artist:'Tô Chấn Phong',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4b1BYZlpOZExvRzQ',
		price:'0',
		duration:'04:34',
		cover:'https://www.mediafire.com/convkey/1426/pc9c6bf29jo1za26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4dXhtWkp1bzFBT2M',
		oga:'#',
		title:'anh thì không',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4dXhtWkp1bzFBT2M',
		price:'0',
		duration:'04:12',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4MWpmSkFqa3Jpa00',
		oga:'#',
		title:'ảo mộng tình yêu',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MWpmSkFqa3Jpa00',
		price:'0',
		duration:'04:23',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4Z3kwaXBiYUlweFE',
		oga:'#',
		title:'biển đời',
		artist:'Lam Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Z3kwaXBiYUlweFE',
		price:'0',
		duration:'04:18',
		cover:'https://www.mediafire.com/convkey/b4c3/hoyrsr1bolld4kt6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4MmNRWVVJQ2NMZlU',
		oga:'#',
		title:'bình minh tình yêu',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MmNRWVVJQ2NMZlU',
		price:'0',
		duration:'05:50',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4SUhyamZjdFVqMXM',
		oga:'#',
		title:'buồn như đá thời gian',
		artist:'Đan Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SUhyamZjdFVqMXM',
		price:'0',
		duration:'03:40',
		cover:'https://www.mediafire.com/convkey/7c4b/1crsv6ndgy3m1re6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4cGpnSlRFb2lmbDg',
		oga:'#',
		title:'bước chân lẻ loi',
		artist:'Đan Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cGpnSlRFb2lmbDg',
		price:'0',
		duration:'04:48',
		cover:'https://www.mediafire.com/convkey/7c4b/1crsv6ndgy3m1re6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4RTh2M3AxNTl6M2M',
		oga:'#',
		title:'cà phê đắng trở lại',
		artist:'Don Hồ',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RTh2M3AxNTl6M2M',
		price:'0',
		duration:'04:11',
		cover:'https://www.mediafire.com/convkey/73b7/n90khlg43q3dwgd6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4S1ROR3p6dUpnQzQ',
		oga:'#',
		title:'chia tay trong mưa',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4S1ROR3p6dUpnQzQ',
		price:'0',
		duration:'05:13',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4RjRWUEVfNHFHdnM',
		oga:'#',
		title:'chiếc lá mùa đông',
		artist:'Nguyễn Hưng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RjRWUEVfNHFHdnM',
		price:'0',
		duration:'04:16',
		cover:'https://www.mediafire.com/convkey/28a6/g2rmmqpbppv8jpl6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4MVlBeURDdENLOUU',
		oga:'#',
		title:'còn lại 1 mình',
		artist:'Đan Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MVlBeURDdENLOUU',
		price:'0',
		duration:'04:20',
		cover:'https://www.mediafire.com/convkey/7c4b/1crsv6ndgy3m1re6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bXJSNTVRVWNzRUE',
		oga:'#',
		title:'con tim mù lòa',
		artist:'Sỹ Đan',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bXJSNTVRVWNzRUE',
		price:'0',
		duration:'04:20',
		cover:'https://www.mediafire.com/convkey/5617/g00eghg7nlo11606g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4blNMLUtTT2NWLWs',
		oga:'#',
		title:'cuộc tình mong manh',
		artist:'Tô Chấn Phong',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4blNMLUtTT2NWLWs',
		price:'0',
		duration:'04:42',
		cover:'https://www.mediafire.com/convkey/1426/pc9c6bf29jo1za26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4d0dLTXl4N2ZWUjQ',
		oga:'#',
		title:'cuộc tình vạn dặm',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4d0dLTXl4N2ZWUjQ',
		price:'0',
		duration:'04:49',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4SGlYYnFqN002OFE',
		oga:'#',
		title:'cứ yêu nhau đi',
		artist:'Nguyễn Đức',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SGlYYnFqN002OFE',
		price:'0',
		duration:'03:37',
		cover:'https://www.mediafire.com/convkey/fc25/68tph32abl7avve6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4VXRWY0pTMEo1SFk',
		oga:'#',
		title:'dáng em',
		artist:'Bằng Kiều',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VXRWY0pTMEo1SFk',
		price:'0',
		duration:'04:41',
		cover:'https://www.mediafire.com/convkey/89c9/x2egl1q5yql2i7b6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4NEtaVG9xam1rQzA',
		oga:'#',
		title:'đã không yêu thì thôi',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NEtaVG9xam1rQzA',
		price:'0',
		duration:'03:42',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4NEZreEtLYnV1SFU',
		oga:'#',
		title:'em sẽ là người ra đi',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NEZreEtLYnV1SFU',
		price:'0',
		duration:'04:14',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UWk1Y0N6RVpGRlk',
		oga:'#',
		title:'hoa nào anh quên',
		artist:'Tô Chấn Phong',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UWk1Y0N6RVpGRlk',
		price:'0',
		duration:'04:43',
		cover:'https://www.mediafire.com/convkey/1426/pc9c6bf29jo1za26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bGViTE1LQkxXOUE',
		oga:'#',
		title:'hoa nào tàn phai',
		artist:'Lưu Bích',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bGViTE1LQkxXOUE',
		price:'0',
		duration:'03:29',
		cover:'https://www.mediafire.com/convkey/cb36/wvlih8mc8527y4x6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ckFiOHBGNWVDTGM',
		oga:'#',
		title:'hoa tàn',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ckFiOHBGNWVDTGM',
		price:'0',
		duration:'04:36',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bURYaFlUQWh4ejA',
		oga:'#',
		title:'hoài mong',
		artist:'Anh Tú',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bURYaFlUQWh4ejA',
		price:'0',
		duration:'04:17',
		cover:'https://www.mediafire.com/convkey/0a26/00awj3s6k4kqczw6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4cFMzcU1IbExmb0U',
		oga:'#',
		title:'không yêu thì thôi',
		artist:'Bằng Kiều',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cFMzcU1IbExmb0U',
		price:'0',
		duration:'04:14',
		cover:'https://www.mediafire.com/convkey/89c9/x2egl1q5yql2i7b6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4THJlMWxQZi1iVHc',
		oga:'#',
		title:'khúc nhạc buồn',
		artist:'Tô Chấn Phong',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4THJlMWxQZi1iVHc',
		price:'0',
		duration:'04:05',
		cover:'https://www.mediafire.com/convkey/1426/pc9c6bf29jo1za26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bUFfT2hDTzZaM1U',
		oga:'#',
		title:'kiếp đỏ đen',
		artist:'Duy Mạnh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bUFfT2hDTzZaM1U',
		price:'0',
		duration:'05:20',
		cover:'https://www.mediafire.com/convkey/2194/a0fp51g3eyi24jt6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=1ZNDWWfm36-NNu--hjlpyQY1g5lUhHi8R',
		oga:'#',
		title:'mây và núi',
		artist:'The Bells',
		rating:5,
		buy:'https://drive.google.com/open?id=1ZNDWWfm36-NNu--hjlpyQY1g5lUhHi8R',
		price:'0',
		duration:'10:11',
		cover:'https://www.mediafire.com/convkey/0566/8zg735pcv7e7v4v6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4cEVvamJzUHFWdUE',
		oga:'#',
		title:'người tình mùa đông',
		artist:'Nhật Hào',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cEVvamJzUHFWdUE',
		price:'0',
		duration:'05:35',
		cover:'https://www.mediafire.com/convkey/bec2/sipu3bn2yjnq94v6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4Y2kwajEzbHlKakE',
		oga:'#',
		title:'những lời dối gian',
		artist:'Tú Quyên',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Y2kwajEzbHlKakE',
		price:'0',
		duration:'04:06',
		cover:'https://www.mediafire.com/convkey/4bf2/stit9ctioji7vnx6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4cEZ5bnk0N28wZlE',
		oga:'#',
		title:'nỗi buồn gác trọ',
		artist:'Đàm Vĩnh Hưng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cEZ5bnk0N28wZlE',
		price:'0',
		duration:'03:52',
		cover:'https://www.mediafire.com/convkey/83f5/7avrca7u752vk7s6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4VWNOTURIZW5JLUU',
		oga:'#',
		title:'nụ hôn biệt ly',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VWNOTURIZW5JLUU',
		price:'0',
		duration:'04:40',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4cDlBZ0FBd2h4LWs',
		oga:'#',
		title:'nụ hồng mong manh',
		artist:'Tú Quyên',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cDlBZ0FBd2h4LWs',
		price:'0',
		duration:'04:29',
		cover:'https://www.mediafire.com/convkey/4bf2/stit9ctioji7vnx6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4OUFoMU1vZlJ4bnM',
		oga:'#',
		title:'phút biệt ly',
		artist:'Cẩm Ly',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4OUFoMU1vZlJ4bnM',
		price:'0',
		duration:'04:28',
		cover:'https://www.mediafire.com/convkey/8b90/8huem6i7pos3jog6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=1WXB0gi9XMwKdAXt4zrCZ7ApaEhkS_v4h',
		oga:'#',
		title:'quên 1 lời thề',
		artist:'Nguyễn Thắng',
		rating:5,
		buy:'https://drive.google.com/open?id=1WXB0gi9XMwKdAXt4zrCZ7ApaEhkS_v4h',
		price:'0',
		duration:'04:26',
		cover:'https://www.mediafire.com/convkey/85ed/uijn9qqr58gzxt76g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=1Isqstr2psE6_X674ylxcXGQdco_zGIJp',
		oga:'#',
		title:'sai lầm vẫn là anh',
		artist:'Nhật Hào',
		rating:5,
		buy:'https://drive.google.com/open?id=1Isqstr2psE6_X674ylxcXGQdco_zGIJp',
		price:'0',
		duration:'04:38',
		cover:'https://www.mediafire.com/convkey/bec2/sipu3bn2yjnq94v6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=1HLRsXNJhegcfjjButI7q5EbbKkRmaN8s',
		oga:'#',
		title:'tàn tro',
		artist:'Nguyễn Thắng',
		rating:5,
		buy:'https://drive.google.com/open?id=1HLRsXNJhegcfjjButI7q5EbbKkRmaN8s',
		price:'0',
		duration:'04:39',
		cover:'https://www.mediafire.com/convkey/85ed/uijn9qqr58gzxt76g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4Z3RIREY4bzBWQ2s',
		oga:'#',
		title:'tâm hồn xao động',
		artist:'Đan Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Z3RIREY4bzBWQ2s',
		price:'0',
		duration:'05:19',
		cover:'https://www.mediafire.com/convkey/7c4b/1crsv6ndgy3m1re6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UVRqSlhRZ0tOaEU',
		oga:'#',
		title:'tiếng sáo phiêu bồng',
		artist:'Lam Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UVRqSlhRZ0tOaEU',
		price:'0',
		duration:'05:51',
		cover:'https://www.mediafire.com/convkey/b4c3/hoyrsr1bolld4kt6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UXk5clhnMUZNY00',
		oga:'#',
		title:'tình đầu chưa nguôi',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UXk5clhnMUZNY00',
		price:'0',
		duration:'04:38',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4SUxXdTFhTnJwdHM',
		oga:'#',
		title:'tình đơn phương',
		artist:'Huy Vũ',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SUxXdTFhTnJwdHM',
		price:'0',
		duration:'04:22',
		cover:'https://www.mediafire.com/convkey/958b/n0h6555r80baoca6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=1japHSs43x-fc7nIxxAUN4VSce4M1Olk2',
		oga:'#',
		title:'tình mãi bên anh',
		artist:'Tú Quyên',
		rating:5,
		buy:'https://drive.google.com/open?id=1japHSs43x-fc7nIxxAUN4VSce4M1Olk2',
		price:'0',
		duration:'03:36',
		cover:'https://www.mediafire.com/convkey/4bf2/stit9ctioji7vnx6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ZlNNNXZGZWhISkE',
		oga:'#',
		title:'tình nhạt phai',
		artist:'Don Hồ',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZlNNNXZGZWhISkE',
		price:'0',
		duration:'03:48',
		cover:'https://www.mediafire.com/convkey/73b7/n90khlg43q3dwgd6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4WFlUYnpZSVF4TlE',
		oga:'#',
		title:'tình như lá bay xa',
		artist:'Jimmy Nguyễn',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4WFlUYnpZSVF4TlE',
		price:'0',
		duration:'03:45',
		cover:'https://www.mediafire.com/convkey/2f34/93mj1atses1aekf6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4QVpFaWFOTzhORkE',
		oga:'#',
		title:'tình phai',
		artist:'Minh Thuận',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4QVpFaWFOTzhORkE',
		price:'0',
		duration:'05:14',
		cover:'https://www.mediafire.com/convkey/bec2/sipu3bn2yjnq94v6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4RVNMb1MzRUx6WVE',
		oga:'#',
		title:'tình xưa nghĩa cũ 3',
		artist:'Jimmy Nguyễn',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RVNMb1MzRUx6WVE',
		price:'0',
		duration:'04:00',
		cover:'https://www.mediafire.com/convkey/2f34/93mj1atses1aekf6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4N0FSZ0NLQUtaWEU',
		oga:'#',
		title:'tôi là tôi',
		artist:'Quách Thành Danh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4N0FSZ0NLQUtaWEU',
		price:'0',
		duration:'04:10',
		cover:'https://www.mediafire.com/convkey/87f3/mk5rp5714s29h3h6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ZmQ4Yy1GWW94aUk',
		oga:'#',
		title:'tôi ngàn năm đợi',
		artist:'Huy Vũ',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZmQ4Yy1GWW94aUk',
		price:'0',
		duration:'05:49',
		cover:'https://www.mediafire.com/convkey/958b/n0h6555r80baoca6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ZHp1QXVjMmxWWEE',
		oga:'#',
		title:'trở lại phố cũ',
		artist:'Đan Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZHp1QXVjMmxWWEE',
		price:'0',
		duration:'05:33',
		cover:'https://www.mediafire.com/convkey/7c4b/1crsv6ndgy3m1re6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UXdJbWdObkVoT0E',
		oga:'#',
		title:'tuyết hồng',
		artist:'Minh Tuyết',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UXdJbWdObkVoT0E',
		price:'0',
		duration:'05:42',
		cover:'https://www.mediafire.com/convkey/5b1f/p29mltgmaj9y41k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4anZKSWpUUGgwSjg',
		oga:'#',
		title:'xin 1 lần được yêu',
		artist:'itvtbadboy',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4anZKSWpUUGgwSjg',
		price:'0',
		duration:'03:52',
		cover:'https://www.mediafire.com/convkey/5ab8/u5f4886rjjtony56g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4VnRaaUhvTS1UQmM',
		oga:'#',
		title:'yêu 1 người',
		artist:'Tô Chấn Phong',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VnRaaUhvTS1UQmM',
		price:'0',
		duration:'04:05',
		cover:'https://www.mediafire.com/convkey/1426/pc9c6bf29jo1za26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4SWtxbW11aTVhNUE',
		oga:'#',
		title:'yêu em trọn đời',
		artist:'Đan Trường',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SWtxbW11aTVhNUE',
		price:'0',
		duration:'04:16',
		cover:'https://www.mediafire.com/convkey/7c4b/1crsv6ndgy3m1re6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4MmhFWEhFazJLSWs',
		oga:'#',
		title:'yêu lầm',
		artist:'Lý Hải',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MmhFWEhFazJLSWs',
		price:'0',
		duration:'04:45',
		cover:'https://www.mediafire.com/convkey/9f97/c2a952fl1idw77g6g.jpg'
	}
];
