var myPlaylist = [
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/1_thu%E1%BB%9F_y%C3%AAu_ng%C6%B0%E1%BB%9Di.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương ngọc hữu: 1 thuở yêu người">1 thuở yêu người</a>',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:41',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/opportunity_dark_as_possible.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lê minh: 7 viên kim cương">7 viên kim cương</a>',
		artist:'Leon Lai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:24',
		cover:'https://i.pinimg.com/originals/6e/0f/be/6e0fbee64b0fffb69661f9ab87816aa3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/c%E1%BB%95_m%C3%A1y_th%E1%BB%9Di_gian.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa cổ thiên lạc: cổ máy thời gian">cổ máy thời gian</a>',
		artist:'Louis Koo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:12',
		cover:'https://i.pinimg.com/originals/65/e4/fa/65e4faf9e8624b7c4c787e0783df15d6.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/c%C3%B2n_l%E1%BA%A1i_n%E1%BB%97i_c%C3%B4_%C4%91%C6%A1n.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: còn lại nỗi cô đơn">còn lại nỗi cô đơn</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/cu%E1%BB%99c_ch%C6%A1i_v%C3%B4_ngh%C4%A9a.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trần tuệ lâm: cuộc chơi vô nghĩa">cuộc chơi vô nghĩa</a>',
		artist:'Kelly Chen',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:09',
		cover:'https://i.pinimg.com/originals/c5/e6/93/c5e693bb265b90eebe8e8ba799e5e133.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/cu%E1%BB%99c_t%C3%ACnh_v%E1%BA%A1n_d%E1%BA%B7m.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: cuộc tình vạn dặm">cuộc tình vạn dặm</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:48',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/d%C3%A1ng_em.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lâm chí huyền: dáng em">dáng em</a>',
		artist:'Terry Lin',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:23',
		cover:'https://i.pinimg.com/originals/47/ce/95/47ce95688bda81c74ff264791392f6ce.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/d%C3%B9_c%C3%B3_l%C3%A0_ng%C6%B0%E1%BB%9Di_t%C3%ACnh.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa quách phú thành: dù có là người tình">dù có là người tình</a>',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:07',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/%C4%91ao_ki%E1%BA%BFm_nh%C6%B0_m%E1%BB%99ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: đao kiếm như mộng">đao kiếm như mộng</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:01',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/%C4%91au-th%C6%B0%C6%A1ng-v%C3%AC-em.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa vũ khải hiền: đau thương chỉ vì em">đau thương chỉ vì em</a>',
		artist:'Eric Moo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/c6/1a/9f/c61a9f2afb7ac4d85724dfc4b4efe00b.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/em_c%C3%B3_y%C3%AAu_anh_kh%C3%B4ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: em có yêu anh không">em có yêu anh không</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:49',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thi%C3%AAn_long_b%C3%A1t_b%E1%BB%99.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa chung hán lương: giang sơn tươi đẹp">giang sơn tươi đẹp</a>',
		artist:'Wallace Chung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'01:59',
		cover:'https://i.pinimg.com/originals/ab/8f/f8/ab8ff8c69f77d8e05bb37311f415bef7.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thanh_ki%E1%BA%BFm_%C4%91%E1%BB%93_long.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa ngô khải hoa: gió mây chuyển sắc">gió mây chuyển sắc</a>',
		artist:'Lawrence Ng',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:18',
		cover:'https://i.pinimg.com/originals/61/e2/75/61e275d76bdbff8d364d3b0c404430a2.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/hao-han-truong-kiet.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương kiệt: hảo hán">hảo hán</a>',
		artist:'Jason Zhang',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:52',
		cover:'https://i.pinimg.com/originals/e5/ad/d0/e5add0e8e65a7a4cd4b3f28da18d11b8.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/hoa_b%E1%BA%B1ng_l%C4%83ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: hoa bằng lăng">hoa bằng lăng</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:28',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/khi_n%C3%A0o_em_m%E1%BB%9Bi_bi%E1%BA%BFt.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: khi nào em mới biết">khi nào em mới biết</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:39',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/kh%C3%BAc_nh%E1%BA%A1c_bu%E1%BB%93n.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa quách phú thành: khúc nhạc buồn">khúc nhạc buồn</a>',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:22',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ki%E1%BA%BFp_ve_s%E1%BA%A7u.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa thái chánh tiêu: kiếp ve sầu">kiếp ve sầu</a>',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:40',
		cover:'https://i.pinimg.com/originals/25/36/0a/25360a7b92f4f9d20da9879ea1c9970a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/kinh_kh%C3%B3_ni%E1%BB%87m.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: kinh khó niệm">kinh khó niệm</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:46',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/loves_first_experiment.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương chấn nhạc: love first experiment">love first experiment</a>',
		artist:'Chang Chen-yue',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:02',
		cover:'https://i.pinimg.com/originals/e9/57/42/e95742d1d88da5e2c4827fa7396e109e.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%81m_l%C3%B2ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa nhậm hiền tề: mềm lòng">mềm lòng</a>',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:54',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%8Bt_m%C3%B9_n%E1%BB%97i_nh%E1%BB%9B.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa diệp tịnh văn: mịt mù nỗi nhớ">mịt mù nỗi nhớ</a>',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:52',
		cover:'https://i.pinimg.com/originals/5c/fe/03/5cfe0318bde3b968720a7026e6c25959.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/moons_heart.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa diệp tịnh văn: moons heart">moons heart</a>',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:28',
		cover:'https://i.pinimg.com/originals/5c/fe/03/5cfe0318bde3b968720a7026e6c25959.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%99ng_%C4%91%E1%BA%B9p_ng%C3%A0y_x%C6%B0a.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: mộng đẹp ngày xưa">mộng đẹp ngày xưa</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'02:40',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%C6%B0a_tr%C3%AAn_cu%E1%BB%99c_t%C3%ACnh.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa tôn lộ: mưa trên cuộc tình">mưa trên cuộc tình</a>',
		artist:'Sun Lu',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:11',
		cover:'https://i.pinimg.com/originals/24/45/0b/24450b943b11b41bfa69c1e6dc4e5c72.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/never_meant_to_hurt_you.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa alex to: never meant to hurt you">never meant to hurt you</a>',
		artist:'Alex To',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:55',
		cover:'https://i.pinimg.com/originals/dd/10/95/dd109500809ca4f9e18486ab3e5135fb.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ng%C3%A0n_5_t%C6%B0%C6%A1ng_ph%C3%B9ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: ngàn năm tương phùng">ngàn năm tương phùng</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:08',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/nh%E1%BB%AFng_l%E1%BB%9Di_d%E1%BB%91i_gian.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: những lời dối gian">những lời dối gian</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'02:34',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/n%E1%BB%A5_h%C3%B4n_bi%E1%BB%87t_ly.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương ngọc hữu: nụ hôn biệt ly">nụ hôn biệt ly</a>',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/n%E1%BB%A5_h%C3%B4n_v%C3%A0_n%C6%B0%E1%BB%9Bc_m%E1%BA%AFt.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: nụ hôn và nước mắt">nụ hôn và nước mắt</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:13',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/n%E1%BB%A5_h%E1%BB%93ng_mong_manh.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa diệp tịnh văn: nụ hồng mong manh">nụ hồng mong manh</a>',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:41',
		cover:'https://i.pinimg.com/originals/5c/fe/03/5cfe0318bde3b968720a7026e6c25959.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/para_para_sakura.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa quách phú thành: para para sakura">para para sakura</a>',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/phong_3_t%C3%ACnh_%C4%91%E1%BB%9Di.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: phong ba tình đời">phong ba tình đời</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:38',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/remember.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa nhậm hiền tề: remember">remember</a>',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:10',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/sai_l%E1%BA%A7m_v%E1%BA%ABn_l%C3%A0_anh.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: sai lầm vẫn là anh">sai lầm vẫn là anh</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:04',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%A2n_s%E1%BB%9F_l%C6%B0u_h%C6%B0%C6%A1ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa nhậm hiền tề: sở lưu hương">sở lưu hương</a>',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/th%E1%BA%A7m_g%E1%BB%8Di_t%C3%AAn_em.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: thầm gọi tên em">thầm gọi tên em</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'08:31',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/th%E1%BA%A7n_%C4%91i%C3%AAu_95.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: thiên hạ hữu tình">thiên hạ hữu tình</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thi%C3%AAn_nhai.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa it vũng tàu badboy: thiên nhai">thiên nhai</a>',
		artist:'thiên nhai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:34',
		cover:'https://i.pinimg.com/originals/8f/6c/39/8f6c39ddb80e3b2d911b24861382775a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thinking_is_useless.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: thinking is useless">thinking is useless</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:13',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ti%E1%BB%85n_b%E1%BA%A1n_l%C3%AAn_%C4%91%C6%B0%E1%BB%9Dng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: tiễn bạn lên đường">tiễn bạn lên đường</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:19',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ti%E1%BA%BFng_s%C3%A1o_phi%C3%AAu_b%E1%BB%93ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: tiếng sáo phiêu bồng">tiếng sáo phiêu bồng</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:19',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ti%E1%BA%BFu_ng%E1%BA%A1o_giang_h%E1%BB%93.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa nhậm hiền tề: tiếu ngạo giang hồ">tiếu ngạo giang hồ</a>',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:30',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_%C4%91%E1%BA%A7u_ch%C6%B0a_ngu%C3%B4i.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương ngọc hữu: tình đầu chưa nguôi">tình đầu chưa nguôi</a>',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_%C4%91%C6%A1n_c%C3%B4i.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: tình đơn côi">tình đơn côi</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:25',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_%C4%91%C6%A1n_ph%C6%B0%C6%A1ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa thái chánh tiêu: tình đơn phương">tình đơn phương</a>',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:30',
		cover:'https://i.pinimg.com/originals/25/36/0a/25360a7b92f4f9d20da9879ea1c9970a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_nh%E1%BA%A1t_phai.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: tình nhạt phai">tình nhạt phai</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_nh%C6%B0_gi%C3%B3_nh%C6%B0_m%C6%B0a.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: tình như gió mưa">tình như gió mưa</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:32',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_s%C3%A2u_bi%E1%BB%83n_c%C3%A0ng_s%C3%A2u.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lê tư: tình sâu biển sâu">tình sâu biển sâu</a>',
		artist:'Gigi Lai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:53',
		cover:'https://i.pinimg.com/originals/f1/73/80/f173806c55ec20b84fe30cb483cccb24.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%B4i_kh%C3%B4ng_tin.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trịnh thiếu thu: tôi không tin">tôi không tin</a>',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:23',
		cover:'https://i.pinimg.com/originals/c5/00/ea/c500ea03b89235352a33ea295d43a6b3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/tr%E1%BB%9F_l%E1%BA%A1i_ph%E1%BB%91_c%C5%A9.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lê minh: trở lại phố cũ">trở lại phố cũ</a>',
		artist:'Leon Lai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:00',
		cover:'https://i.pinimg.com/originals/6e/0f/be/6e0fbee64b0fffb69661f9ab87816aa3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C6%B0%C6%A1ng_t%C6%B0_trong_m%C6%B0a.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương ngọc hữu: tương tư trong mưa">tương tư trong mưa</a>',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/v%E1%BA%A7ng_tr%C4%83ng_kh%C3%B3c.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: vầng trăng khóc">vầng trăng khóc</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:22',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/v%E1%BA%BFt_th%C6%B0%C6%A1ng_l%C3%B2ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: vết thương lòng">vết thương lòng</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:22',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/v%C3%AC_1_ng%C6%B0%E1%BB%9Di_ra_%C4%91i.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trịnh thiếu thu: vì 1 người ra đi">vì 1 người ra đi</a>',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:27',
		cover:'https://i.pinimg.com/originals/c5/00/ea/c500ea03b89235352a33ea295d43a6b3.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SnhxYlB1MnFsems',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương ngọc hữu: yêu em">yêu em</a>',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:55',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	}
];
