var myPlaylist = [
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/1_thu%E1%BB%9F_y%C3%AAu_ng%C6%B0%E1%BB%9Di.mp3',
		oga:'#',
		title:'1 thuở yêu người',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:41',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4dFRFckoxYTZ6ZU0',
		oga:'#',
		title:'7 viên kim cương',
		artist:'Leon Lai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4dFRFckoxYTZ6ZU0',
		price:'0',
		duration:'03:24',
		cover:'https://www.mediafire.com/convkey/475c/bf5ocz9tqf5gbs36g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4MWtJRUdUQ2dfQW8',
		oga:'#',
		title:'cổ máy thời gian',
		artist:'Louis Koo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MWtJRUdUQ2dfQW8',
		price:'0',
		duration:'03:12',
		cover:'https://www.mediafire.com/convkey/c271/h96yymxgecm5v4c6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Tkl6MmVGVUhSNFE',
		oga:'#',
		title:'còn lại nỗi cô đơn',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Tkl6MmVGVUhSNFE',
		price:'0',
		duration:'04:35',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4WHlwSkRlU0VnMXM',
		oga:'#',
		title:'cuộc chơi vô nghĩa',
		artist:'Kelly Chen',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4WHlwSkRlU0VnMXM',
		price:'0',
		duration:'04:09',
		cover:'https://www.mediafire.com/convkey/c690/iyy7fd7g7bun6ro6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4MF80Wjd1SHZZQ1E',
		oga:'#',
		title:'cuộc tình vạn dặm',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MF80Wjd1SHZZQ1E',
		price:'0',
		duration:'03:48',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4b1F6YU5vb1k1bVk',
		oga:'#',
		title:'dáng em',
		artist:'Terry Lin',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4b1F6YU5vb1k1bVk',
		price:'0',
		duration:'04:23',
		cover:'https://www.mediafire.com/convkey/0765/f1yq4ajvbttha4k6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4UnkweTE1WWVuRjQ',
		oga:'#',
		title:'dù có là người tình',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UnkweTE1WWVuRjQ',
		price:'0',
		duration:'03:07',
		cover:'https://www.mediafire.com/convkey/c900/cfku9ldvvk3oc2y6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=1Jj3AzwNMrNi2rMbDrV09rrMvWh1nQgY2',
		oga:'#',
		title:'đao kiếm như mộng',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=1Jj3AzwNMrNi2rMbDrV09rrMvWh1nQgY2',
		price:'0',
		duration:'03:01',
		cover:'https://www.mediafire.com/convkey/7507/zyc8rvsyncjypb86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=1w8aML4_8hD56dXBY_XTfCsT1B4Xo-lXW',
		oga:'#',
		title:'đau thương chỉ vì em',
		artist:'Eric Moo',
		rating:5,
		buy:'https://drive.google.com/open?id=1w8aML4_8hD56dXBY_XTfCsT1B4Xo-lXW',
		price:'0',
		duration:'04:14',
		cover:'https://www.mediafire.com/convkey/c662/o0q0r7sq6c4gha26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4NXBRN2tiSGgyUlk',
		oga:'#',
		title:'em có yêu anh không',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NXBRN2tiSGgyUlk',
		price:'0',
		duration:'03:49',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4NFFNM3B4aF9reUE',
		oga:'#',
		title:'giang sơn tươi đẹp',
		artist:'Wallace Chung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NFFNM3B4aF9reUE',
		price:'0',
		duration:'01:59',
		cover:'https://www.mediafire.com/convkey/9302/3x7dh4n4hsimbz26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4NV9NUlFPM1R1Y2c',
		oga:'#',
		title:'gió mây chuyển sắc',
		artist:'Lawrence Ng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NV9NUlFPM1R1Y2c',
		price:'0',
		duration:'03:18',
		cover:'https://www.mediafire.com/convkey/07eb/mh7038xgjnhkoo96g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=1Bl9jjeOVxqVZ1udWkwz_WhPPk-eJMYHe',
		oga:'#',
		title:'hảo hán',
		artist:'Jason Zhang',
		rating:5,
		buy:'https://drive.google.com/open?id=1Bl9jjeOVxqVZ1udWkwz_WhPPk-eJMYHe',
		price:'0',
		duration:'03:52',
		cover:'https://www.mediafire.com/convkey/da58/4brfd6q50jywm9w6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4WG9fc29VbmtkQ2M',
		oga:'#',
		title:'hoa bằng lăng',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4WG9fc29VbmtkQ2M',
		price:'0',
		duration:'03:28',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4aVduS3pOWFE2SXM',
		oga:'#',
		title:'khi nào em mới biết',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4aVduS3pOWFE2SXM',
		price:'0',
		duration:'04:39',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4T1AtYlFldXBBZHM',
		oga:'#',
		title:'khúc nhạc buồn',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4T1AtYlFldXBBZHM',
		price:'0',
		duration:'04:22',
		cover:'https://www.mediafire.com/convkey/c900/cfku9ldvvk3oc2y6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4dWhUVm9qVUwycWs',
		oga:'#',
		title:'kiếp ve sầu',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4dWhUVm9qVUwycWs',
		price:'0',
		duration:'03:40',
		cover:'https://www.mediafire.com/convkey/9d0f/al77p5c4we95e9d6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4b2hpSGJnazBUQjA',
		oga:'#',
		title:'kinh khó niệm',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4b2hpSGJnazBUQjA',
		price:'0',
		duration:'04:46',
		cover:'https://www.mediafire.com/convkey/7507/zyc8rvsyncjypb86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4bUpWLU96eWdNMXc',
		oga:'#',
		title:'love first experiment',
		artist:'Chang Chen-yue',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bUpWLU96eWdNMXc',
		price:'0',
		duration:'04:02',
		cover:'https://www.mediafire.com/convkey/09ff/nnysqlgp83anyms6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Tmc3S1VNZHFSczg',
		oga:'#',
		title:'mềm lòng',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Tmc3S1VNZHFSczg',
		price:'0',
		duration:'05:54',
		cover:'https://www.mediafire.com/convkey/3513/1y9zrjz748bwllo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4LTNnemxiS05OYkU',
		oga:'#',
		title:'mịt mù nỗi nhớ',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4LTNnemxiS05OYkU',
		price:'0',
		duration:'03:52',
		cover:'https://www.mediafire.com/convkey/3ebc/go86zjllcjah6c66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4N09CMGxSeUNLMmM',
		oga:'#',
		title:'moons heart',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4N09CMGxSeUNLMmM',
		price:'0',
		duration:'04:28',
		cover:'https://www.mediafire.com/convkey/3ebc/go86zjllcjah6c66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4V3ZjOUIzMVZHcUU',
		oga:'#',
		title:'mộng đẹp ngày xưa',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4V3ZjOUIzMVZHcUU',
		price:'0',
		duration:'02:40',
		cover:'https://www.mediafire.com/convkey/7507/zyc8rvsyncjypb86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4QkV6ZTh1LTZDRms',
		oga:'#',
		title:'mưa trên cuộc tình',
		artist:'Sun Lu',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4QkV6ZTh1LTZDRms',
		price:'0',
		duration:'04:11',
		cover:'https://www.mediafire.com/convkey/d7ac/dz9b0kw5f45tlio6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4TEtCVjk4dG82UUE',
		oga:'#',
		title:'never meant to hurt you',
		artist:'Alex To',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4TEtCVjk4dG82UUE',
		price:'0',
		duration:'04:55',
		cover:'https://www.mediafire.com/convkey/90ac/v87xau8bo2gflj66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4bXA2V3RxenVKZ1E',
		oga:'#',
		title:'ngàn năm tương phùng',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bXA2V3RxenVKZ1E',
		price:'0',
		duration:'04:08',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Y09iSDFMNy1GWVk',
		oga:'#',
		title:'những lời dối gian',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Y09iSDFMNy1GWVk',
		price:'0',
		duration:'02:34',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4WWhuWDZqb0dLSm8',
		oga:'#',
		title:'nụ hôn biệt ly',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4WWhuWDZqb0dLSm8',
		price:'0',
		duration:'05:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Zll3bkhCa21TTXc',
		oga:'#',
		title:'nụ hôn và nước mắt',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Zll3bkhCa21TTXc',
		price:'0',
		duration:'05:13',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4UEQyb1pOWE5uQ1E',
		oga:'#',
		title:'nụ hồng mong manh',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UEQyb1pOWE5uQ1E',
		price:'0',
		duration:'04:41',
		cover:'https://www.mediafire.com/convkey/3ebc/go86zjllcjah6c66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4c1pyRkRKM0xNTW8',
		oga:'#',
		title:'para para sakura',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4c1pyRkRKM0xNTW8',
		price:'0',
		duration:'03:55',
		cover:'https://www.mediafire.com/convkey/c900/cfku9ldvvk3oc2y6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4V3hMVzh6R19NRGc',
		oga:'#',
		title:'phong ba tình đời',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4V3hMVzh6R19NRGc',
		price:'0',
		duration:'03:38',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eFNCNFBwcGFwSGc',
		oga:'#',
		title:'remember',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eFNCNFBwcGFwSGc',
		price:'0',
		duration:'03:10',
		cover:'https://www.mediafire.com/convkey/3513/1y9zrjz748bwllo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4cXl6YkF5NlloQ28',
		oga:'#',
		title:'sai lầm vẫn là anh',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cXl6YkF5NlloQ28',
		price:'0',
		duration:'04:04',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4TmMzUlprbGJrWVE',
		oga:'#',
		title:'sở lưu hương',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4TmMzUlprbGJrWVE',
		price:'0',
		duration:'04:35',
		cover:'https://www.mediafire.com/convkey/3513/1y9zrjz748bwllo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4OGZfTnNVT1lvbzg',
		oga:'#',
		title:'thầm gọi tên em',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4OGZfTnNVT1lvbzg',
		price:'0',
		duration:'08:31',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4VHFPdEF3ZGp4UXM',
		oga:'#',
		title:'thiên hạ hữu tình',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VHFPdEF3ZGp4UXM',
		price:'0',
		duration:'04:14',
		cover:'https://www.mediafire.com/convkey/7507/zyc8rvsyncjypb86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4U3pCb3MyalNaZ0k',
		oga:'#',
		title:'thiên nhai',
		artist:'thiên nhai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4U3pCb3MyalNaZ0k',
		price:'0',
		duration:'04:34',
		cover:'https://www.mediafire.com/convkey/b3e0/65rl8tzsfn5fezo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4UXI4OXBaWUJGVk0',
		oga:'#',
		title:'thinking is useless',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UXI4OXBaWUJGVk0',
		price:'0',
		duration:'04:13',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Rk9UYmVDQnVwVVE',
		oga:'#',
		title:'tiễn bạn lên đường',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Rk9UYmVDQnVwVVE',
		price:'0',
		duration:'04:19',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eUpvZFlPUzQwN1E',
		oga:'#',
		title:'tiếng sáo phiêu bồng',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eUpvZFlPUzQwN1E',
		price:'0',
		duration:'03:19',
		cover:'https://www.mediafire.com/convkey/7507/zyc8rvsyncjypb86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4dnkwaUlBa00weG8',
		oga:'#',
		title:'tiếu ngạo giang hồ',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4dnkwaUlBa00weG8',
		price:'0',
		duration:'04:30',
		cover:'https://www.mediafire.com/convkey/3513/1y9zrjz748bwllo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4NmhxWDdwTlpkaG8',
		oga:'#',
		title:'tình đầu chưa nguôi',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NmhxWDdwTlpkaG8',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eXU1Tk9OenB2Ykk',
		oga:'#',
		title:'tình đơn côi',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eXU1Tk9OenB2Ykk',
		price:'0',
		duration:'04:25',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RnoxbktUSUFONVk',
		oga:'#',
		title:'tình đơn phương',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RnoxbktUSUFONVk',
		price:'0',
		duration:'04:30',
		cover:'https://www.mediafire.com/convkey/9d0f/al77p5c4we95e9d6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SlN1bWQ3dVpMZnM',
		oga:'#',
		title:'tình nhạt phai',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SlN1bWQ3dVpMZnM',
		price:'0',
		duration:'03:55',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4ZW5jbnJPUFlRSlk',
		oga:'#',
		title:'tình như gió mưa',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZW5jbnJPUFlRSlk',
		price:'0',
		duration:'04:32',
		cover:'https://www.mediafire.com/convkey/5623/wmt1irbf3qpcu8u6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SGtFaHgtNmZMZjA',
		oga:'#',
		title:'tình sâu biển sâu',
		artist:'Gigi Lai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SGtFaHgtNmZMZjA',
		price:'0',
		duration:'04:53',
		cover:'https://www.mediafire.com/convkey/0adc/yxby6dommop2f8s6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eTY3TmdfeHpKTm8',
		oga:'#',
		title:'tôi không tin',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eTY3TmdfeHpKTm8',
		price:'0',
		duration:'03:23',
		cover:'https://www.mediafire.com/convkey/c919/2722zr9pxf3ln1h6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4VmZEVzBUMHdqLWs',
		oga:'#',
		title:'trở lại phố cũ',
		artist:'Leon Lai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VmZEVzBUMHdqLWs',
		price:'0',
		duration:'05:00',
		cover:'https://www.mediafire.com/convkey/475c/bf5ocz9tqf5gbs36g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4ZTE4U1Q0MVJrazQ',
		oga:'#',
		title:'tương tư trong mưa',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZTE4U1Q0MVJrazQ',
		price:'0',
		duration:'04:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4cVlBUmNUVDNoTXc',
		oga:'#',
		title:'vầng trăng khóc',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cVlBUmNUVDNoTXc',
		price:'0',
		duration:'05:22',
		cover:'https://www.mediafire.com/convkey/7507/zyc8rvsyncjypb86g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RndBbFdybEVkS3M',
		oga:'#',
		title:'vết thương lòng',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RndBbFdybEVkS3M',
		price:'0',
		duration:'04:22',
		cover:'https://www.mediafire.com/convkey/dafd/grf0fclxcogczt26g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eXlaRHdwNmttckE',
		oga:'#',
		title:'vì 1 người ra đi',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eXlaRHdwNmttckE',
		price:'0',
		duration:'04:27',
		cover:'https://www.mediafire.com/convkey/c919/2722zr9pxf3ln1h6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SnhxYlB1MnFsems',
		oga:'#',
		title:'yêu em',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SnhxYlB1MnFsems',
		price:'0',
		duration:'05:55',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	}
];
