var myPlaylist = [
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/1_thu%E1%BB%9F_y%C3%AAu_ng%C6%B0%E1%BB%9Di.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương ngọc hữu: 1 thuở yêu người">1 thuở yêu người</a>',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:41',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/opportunity_dark_as_possible.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lê minh: 7 viên kim cương">7 viên kim cương</a>',
		artist:'Leon Lai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:24',
		cover:'https://i.pinimg.com/originals/6e/0f/be/6e0fbee64b0fffb69661f9ab87816aa3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/c%E1%BB%95_m%C3%A1y_th%E1%BB%9Di_gian.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa cổ thiên lạc: cổ máy thời gian">cổ máy thời gian</a>',
		artist:'Louis Koo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:12',
		cover:'https://i.pinimg.com/originals/65/e4/fa/65e4faf9e8624b7c4c787e0783df15d6.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/c%C3%B2n_l%E1%BA%A1i_n%E1%BB%97i_c%C3%B4_%C4%91%C6%A1n.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: còn lại nỗi cô đơn">còn lại nỗi cô đơn</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/cu%E1%BB%99c_ch%C6%A1i_v%C3%B4_ngh%C4%A9a.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trần tuệ lâm: cuộc chơi vô nghĩa">cuộc chơi vô nghĩa</a>',
		artist:'Kelly Chen',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:09',
		cover:'https://i.pinimg.com/originals/c5/e6/93/c5e693bb265b90eebe8e8ba799e5e133.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/cu%E1%BB%99c_t%C3%ACnh_v%E1%BA%A1n_d%E1%BA%B7m.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: cuộc tình vạn dặm">cuộc tình vạn dặm</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:48',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/d%C3%A1ng_em.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lâm chí huyền: dáng em">dáng em</a>',
		artist:'Terry Lin',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:23',
		cover:'https://i.pinimg.com/originals/47/ce/95/47ce95688bda81c74ff264791392f6ce.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/d%C3%B9_c%C3%B3_l%C3%A0_ng%C6%B0%E1%BB%9Di_t%C3%ACnh.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa quách phú thành: dù có là người tình">dù có là người tình</a>',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:07',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/%C4%91ao_ki%E1%BA%BFm_nh%C6%B0_m%E1%BB%99ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: đao kiếm như mộng">đao kiếm như mộng</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:01',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/%C4%91au-th%C6%B0%C6%A1ng-v%C3%AC-em.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa vũ khải hiền: đau thương chỉ vì em">đau thương chỉ vì em</a>',
		artist:'Eric Moo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/c6/1a/9f/c61a9f2afb7ac4d85724dfc4b4efe00b.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/em_c%C3%B3_y%C3%AAu_anh_kh%C3%B4ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: em có yêu anh không">em có yêu anh không</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:49',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thi%C3%AAn_long_b%C3%A1t_b%E1%BB%99.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa chung hán lương: giang sơn tươi đẹp">giang sơn tươi đẹp</a>',
		artist:'Wallace Chung',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'01:59',
		cover:'https://i.pinimg.com/originals/ab/8f/f8/ab8ff8c69f77d8e05bb37311f415bef7.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thanh_ki%E1%BA%BFm_%C4%91%E1%BB%93_long.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa ngô khải hoa: gió mây chuyển sắc">gió mây chuyển sắc</a>',
		artist:'Lawrence Ng',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:18',
		cover:'https://i.pinimg.com/originals/61/e2/75/61e275d76bdbff8d364d3b0c404430a2.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/hao-han-truong-kiet.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương kiệt: hảo hán">hảo hán</a>',
		artist:'Jason Zhang',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:52',
		cover:'https://i.pinimg.com/originals/e5/ad/d0/e5add0e8e65a7a4cd4b3f28da18d11b8.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/hoa_b%E1%BA%B1ng_l%C4%83ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trác y đình: hoa bằng lăng">hoa bằng lăng</a>',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:28',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/khi_n%C3%A0o_em_m%E1%BB%9Bi_bi%E1%BA%BFt.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa lưu đức hoa: khi nào em mới biết">khi nào em mới biết</a>',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:39',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/kh%C3%BAc_nh%E1%BA%A1c_bu%E1%BB%93n.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa quách phú thành: khúc nhạc buồn">khúc nhạc buồn</a>',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:22',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ki%E1%BA%BFp_ve_s%E1%BA%A7u.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa thái chánh tiêu: kiếp ve sầu">kiếp ve sầu</a>',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'03:40',
		cover:'https://www.mediafire.com/convkey/9d0f/al77p5c4we95e9d6g.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/kinh_kh%C3%B3_ni%E1%BB%87m.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa châu hoa kiện: kinh khó niệm">kinh khó niệm</a>',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:46',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/loves_first_experiment.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa trương chấn nhạc: love first experiment">love first experiment</a>',
		artist:'Chang Chen-yue',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'04:02',
		cover:'https://i.pinimg.com/originals/e9/57/42/e95742d1d88da5e2c4827fa7396e109e.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%81m_l%C3%B2ng.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa nhậm hiền tề: mềm lòng">mềm lòng</a>',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.com/nhac-chon-loc/top-1-thoi-nhac-hoa.html',
		price:'0',
		duration:'05:54',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4LTNnemxiS05OYkU',
		oga:'#',
		title:'mịt mù nỗi nhớ',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4LTNnemxiS05OYkU',
		price:'0',
		duration:'03:52',
		cover:'https://www.mediafire.com/convkey/3ebc/go86zjllcjah6c66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4N09CMGxSeUNLMmM',
		oga:'#',
		title:'moons heart',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4N09CMGxSeUNLMmM',
		price:'0',
		duration:'04:28',
		cover:'https://www.mediafire.com/convkey/3ebc/go86zjllcjah6c66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4V3ZjOUIzMVZHcUU',
		oga:'#',
		title:'mộng đẹp ngày xưa',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4V3ZjOUIzMVZHcUU',
		price:'0',
		duration:'02:40',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4QkV6ZTh1LTZDRms',
		oga:'#',
		title:'mưa trên cuộc tình',
		artist:'Sun Lu',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4QkV6ZTh1LTZDRms',
		price:'0',
		duration:'04:11',
		cover:'https://www.mediafire.com/convkey/d7ac/dz9b0kw5f45tlio6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4TEtCVjk4dG82UUE',
		oga:'#',
		title:'never meant to hurt you',
		artist:'Alex To',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4TEtCVjk4dG82UUE',
		price:'0',
		duration:'04:55',
		cover:'https://www.mediafire.com/convkey/90ac/v87xau8bo2gflj66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4bXA2V3RxenVKZ1E',
		oga:'#',
		title:'ngàn năm tương phùng',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bXA2V3RxenVKZ1E',
		price:'0',
		duration:'04:08',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Y09iSDFMNy1GWVk',
		oga:'#',
		title:'những lời dối gian',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Y09iSDFMNy1GWVk',
		price:'0',
		duration:'02:34',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4WWhuWDZqb0dLSm8',
		oga:'#',
		title:'nụ hôn biệt ly',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4WWhuWDZqb0dLSm8',
		price:'0',
		duration:'05:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Zll3bkhCa21TTXc',
		oga:'#',
		title:'nụ hôn và nước mắt',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Zll3bkhCa21TTXc',
		price:'0',
		duration:'05:13',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4UEQyb1pOWE5uQ1E',
		oga:'#',
		title:'nụ hồng mong manh',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UEQyb1pOWE5uQ1E',
		price:'0',
		duration:'04:41',
		cover:'https://www.mediafire.com/convkey/3ebc/go86zjllcjah6c66g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4c1pyRkRKM0xNTW8',
		oga:'#',
		title:'para para sakura',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4c1pyRkRKM0xNTW8',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4V3hMVzh6R19NRGc',
		oga:'#',
		title:'phong ba tình đời',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4V3hMVzh6R19NRGc',
		price:'0',
		duration:'03:38',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eFNCNFBwcGFwSGc',
		oga:'#',
		title:'remember',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eFNCNFBwcGFwSGc',
		price:'0',
		duration:'03:10',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4cXl6YkF5NlloQ28',
		oga:'#',
		title:'sai lầm vẫn là anh',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cXl6YkF5NlloQ28',
		price:'0',
		duration:'04:04',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4TmMzUlprbGJrWVE',
		oga:'#',
		title:'sở lưu hương',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4TmMzUlprbGJrWVE',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4OGZfTnNVT1lvbzg',
		oga:'#',
		title:'thầm gọi tên em',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4OGZfTnNVT1lvbzg',
		price:'0',
		duration:'08:31',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4VHFPdEF3ZGp4UXM',
		oga:'#',
		title:'thiên hạ hữu tình',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VHFPdEF3ZGp4UXM',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4U3pCb3MyalNaZ0k',
		oga:'#',
		title:'thiên nhai',
		artist:'thiên nhai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4U3pCb3MyalNaZ0k',
		price:'0',
		duration:'04:34',
		cover:'https://www.mediafire.com/convkey/b3e0/65rl8tzsfn5fezo6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4UXI4OXBaWUJGVk0',
		oga:'#',
		title:'thinking is useless',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UXI4OXBaWUJGVk0',
		price:'0',
		duration:'04:13',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4Rk9UYmVDQnVwVVE',
		oga:'#',
		title:'tiễn bạn lên đường',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Rk9UYmVDQnVwVVE',
		price:'0',
		duration:'04:19',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eUpvZFlPUzQwN1E',
		oga:'#',
		title:'tiếng sáo phiêu bồng',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eUpvZFlPUzQwN1E',
		price:'0',
		duration:'03:19',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4dnkwaUlBa00weG8',
		oga:'#',
		title:'tiếu ngạo giang hồ',
		artist:'Richie Ren',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4dnkwaUlBa00weG8',
		price:'0',
		duration:'04:30',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4NmhxWDdwTlpkaG8',
		oga:'#',
		title:'tình đầu chưa nguôi',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NmhxWDdwTlpkaG8',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eXU1Tk9OenB2Ykk',
		oga:'#',
		title:'tình đơn côi',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eXU1Tk9OenB2Ykk',
		price:'0',
		duration:'04:25',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RnoxbktUSUFONVk',
		oga:'#',
		title:'tình đơn phương',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RnoxbktUSUFONVk',
		price:'0',
		duration:'04:30',
		cover:'https://www.mediafire.com/convkey/9d0f/al77p5c4we95e9d6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SlN1bWQ3dVpMZnM',
		oga:'#',
		title:'tình nhạt phai',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SlN1bWQ3dVpMZnM',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4ZW5jbnJPUFlRSlk',
		oga:'#',
		title:'tình như gió mưa',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZW5jbnJPUFlRSlk',
		price:'0',
		duration:'04:32',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SGtFaHgtNmZMZjA',
		oga:'#',
		title:'tình sâu biển sâu',
		artist:'Gigi Lai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SGtFaHgtNmZMZjA',
		price:'0',
		duration:'04:53',
		cover:'https://www.mediafire.com/convkey/0adc/yxby6dommop2f8s6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eTY3TmdfeHpKTm8',
		oga:'#',
		title:'tôi không tin',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eTY3TmdfeHpKTm8',
		price:'0',
		duration:'03:23',
		cover:'https://www.mediafire.com/convkey/c919/2722zr9pxf3ln1h6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4VmZEVzBUMHdqLWs',
		oga:'#',
		title:'trở lại phố cũ',
		artist:'Leon Lai',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VmZEVzBUMHdqLWs',
		price:'0',
		duration:'05:00',
		cover:'https://i.pinimg.com/originals/6e/0f/be/6e0fbee64b0fffb69661f9ab87816aa3.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4ZTE4U1Q0MVJrazQ',
		oga:'#',
		title:'tương tư trong mưa',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZTE4U1Q0MVJrazQ',
		price:'0',
		duration:'04:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4cVlBUmNUVDNoTXc',
		oga:'#',
		title:'vầng trăng khóc',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cVlBUmNUVDNoTXc',
		price:'0',
		duration:'05:22',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4RndBbFdybEVkS3M',
		oga:'#',
		title:'vết thương lòng',
		artist:'Andy Lau',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RndBbFdybEVkS3M',
		price:'0',
		duration:'04:22',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4eXlaRHdwNmttckE',
		oga:'#',
		title:'vì 1 người ra đi',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eXlaRHdwNmttckE',
		price:'0',
		duration:'04:27',
		cover:'https://www.mediafire.com/convkey/c919/2722zr9pxf3ln1h6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=view&id=0BxTvT8zcUBb4SnhxYlB1MnFsems',
		oga:'#',
		title:'yêu em',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SnhxYlB1MnFsems',
		price:'0',
		duration:'05:55',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	}
];
