var myPlaylist = [
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4VG9TaGxqa04xMHM',
		oga:'#',
		title:'caravan of life',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4VG9TaGxqa04xMHM',
		price:'0',
		duration:'04:13',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UHFMcjJOQ1FuTnM',
		oga:'#',
		title:'cô đơn 1 vì sao',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UHFMcjJOQ1FuTnM',
		price:'0',
		duration:'05:36',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4dkEwdlNHYm1fdjg',
		oga:'#',
		title:'eternal flame',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4dkEwdlNHYm1fdjg',
		price:'0',
		duration:'03:24',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bm5wVkJoYjNkXzg',
		oga:'#',
		title:'hoa bằng lăng',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bm5wVkJoYjNkXzg',
		price:'0',
		duration:'04:50',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4RzNzdVNSbU1jTlk',
		oga:'#',
		title:'lặng lẽ mùa đông',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4RzNzdVNSbU1jTlk',
		price:'0',
		duration:'04:28',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4QS1QQjhUQ3FheTg',
		oga:'#',
		title:'mỏi mòn',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4QS1QQjhUQ3FheTg',
		price:'0',
		duration:'04:56',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4QTFINXBZUElMZVk',
		oga:'#',
		title:'1 kiếp phong ba',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4QTFINXBZUElMZVk',
		price:'0',
		duration:'04:02',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ako3Y082bXJOdWs',
		oga:'#',
		title:'nguyệt tình',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ako3Y082bXJOdWs',
		price:'0',
		duration:'03:10',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4aG00eUxCVXpRT2M',
		oga:'#',
		title:'nhớ em nhiều hơn',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4aG00eUxCVXpRT2M',
		price:'0',
		duration:'03:24',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4R1hTaTItTURQWGc',
		oga:'#',
		title:'nụ hôn và nước mắt',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4R1hTaTItTURQWGc',
		price:'0',
		duration:'05:10',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4eDZmY21hcVdJa3c',
		oga:'#',
		title:'nụ hồng mong manh',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4eDZmY21hcVdJa3c',
		price:'0',
		duration:'04:29',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4cWItU2JsS0R2RTA',
		oga:'#',
		title:'take me to your heart',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4cWItU2JsS0R2RTA',
		price:'0',
		duration:'05:26',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4Y2pQMV9wRDdtZzA',
		oga:'#',
		title:'thần thoại',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Y2pQMV9wRDdtZzA',
		price:'0',
		duration:'04:50',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bVhjZktvUS1pOFE',
		oga:'#',
		title:'thiên sinh nhai',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bVhjZktvUS1pOFE',
		price:'0',
		duration:'02:27',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bms5VWJPZWVsSjQ',
		oga:'#',
		title:'thu muộn',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bms5VWJPZWVsSjQ',
		price:'0',
		duration:'03:44',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4Z0JmeUpTN284YVE',
		oga:'#',
		title:'tiếu ngạo giang hồ',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Z0JmeUpTN284YVE',
		price:'0',
		duration:'03:14',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UFBHUWRxQ2ZFOVk',
		oga:'#',
		title:'tình xưa nghĩa cũ 1',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UFBHUWRxQ2ZFOVk',
		price:'0',
		duration:'04:15',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4X3A5UFhLY21taXc',
		oga:'#',
		title:'tình xưa nghĩa cũ 2',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4X3A5UFhLY21taXc',
		price:'0',
		duration:'03:51',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4bGVkWmhFdTg5R0U',
		oga:'#',
		title:'tôi sẽ không yêu',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4bGVkWmhFdTg5R0U',
		price:'0',
		duration:'04:04',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4Wm5PVVF3Vi1fY0k',
		oga:'#',
		title:'vì anh yêu em',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4Wm5PVVF3Vi1fY0k',
		price:'0',
		duration:'04:35',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ZGZDVlhzczJaZWs',
		oga:'#',
		title:'yêu 1 người',
		artist:'sáo trúc',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZGZDVlhzczJaZWs',
		price:'0',
		duration:'04:04',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4R042ZllTLVQ0Rkk',
		oga:'#',
		title:'999 đóa hồng',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4R042ZllTLVQ0Rkk',
		price:'0',
		duration:'04:18',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4N2NrOV9jcGFmTTQ',
		oga:'#',
		title:'ảo mộng tình yêu',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4N2NrOV9jcGFmTTQ',
		price:'0',
		duration:'04:14',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UlNnV1J6MHRza1U',
		oga:'#',
		title:'chiếc lá mùa đông',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UlNnV1J6MHRza1U',
		price:'0',
		duration:'04:03',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4TkFhcHhfWi1Oanc',
		oga:'#',
		title:'còn lại nhớ thương',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4TkFhcHhfWi1Oanc',
		price:'0',
		duration:'03:55',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4c2tub2hhV3NvUTA',
		oga:'#',
		title:'đôi bướm bay lượn',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4c2tub2hhV3NvUTA',
		price:'0',
		duration:'03:53',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4MWFFUTlZTW5PYmc',
		oga:'#',
		title:'đường về 2 thôn',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4MWFFUTlZTW5PYmc',
		price:'0',
		duration:'03:53',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4enFhUHo4N2o0THc',
		oga:'#',
		title:'endless love',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4enFhUHo4N2o0THc',
		price:'0',
		duration:'02:31',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4UGF3VDJQVFQyMmc',
		oga:'#',
		title:'giấc mơ 1 cuộc tình',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4UGF3VDJQVFQyMmc',
		price:'0',
		duration:'04:00',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4clVsdERaakYtdGc',
		oga:'#',
		title:'không tên',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4clVsdERaakYtdGc',
		price:'0',
		duration:'02:38',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4c2xpSXhVdzE5RWM',
		oga:'#',
		title:'lỗi lầm đã qua',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4c2xpSXhVdzE5RWM',
		price:'0',
		duration:'04:57',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4NU1JMnZ6aE56Tkk',
		oga:'#',
		title:'mộng uyên ương hồ điệp',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NU1JMnZ6aE56Tkk',
		price:'0',
		duration:'03:56',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4SGN1QVZMV21aQVE',
		oga:'#',
		title:'1 nhành mai',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4SGN1QVZMV21aQVE',
		price:'0',
		duration:'03:35',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4ZHNKTmhKYzE4aEE',
		oga:'#',
		title:'tiếng sáo phiêu bồng',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4ZHNKTmhKYzE4aEE',
		price:'0',
		duration:'02:31',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4b0RsTmdjYVVuTDQ',
		oga:'#',
		title:'tomorrow will come',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4b0RsTmdjYVVuTDQ',
		price:'0',
		duration:'05:04',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	},
	{
		mp3:'https://drive.google.com/uc?export=download&id=0BxTvT8zcUBb4NU5ScGVLbkNxT2M',
		oga:'#',
		title:'tương tư trong mưa',
		artist:'đàn tranh',
		rating:5,
		buy:'https://drive.google.com/open?id=0BxTvT8zcUBb4NU5ScGVLbkNxT2M',
		price:'0',
		duration:'04:06',
		cover:'https://www.mediafire.com/convkey/4e1d/3if40knl62fko3a6g.jpg'
	}
];
