var myPlaylist = [
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/1_thu%E1%BB%9F_y%C3%AAu_ng%C6%B0%E1%BB%9Di.mp3',
		oga:'#',
		title:'1 thuở yêu người',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:41',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/opportunity_dark_as_possible.mp3',
		oga:'#',
		title:'7 viên kim cương',
		artist:'Leon Lai',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:24',
		cover:'https://i.pinimg.com/originals/6e/0f/be/6e0fbee64b0fffb69661f9ab87816aa3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/c%E1%BB%95_m%C3%A1y_th%E1%BB%9Di_gian.mp3',
		oga:'#',
		title:'cổ máy thời gian',
		artist:'Louis Koo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:12',
		cover:'https://i.pinimg.com/originals/65/e4/fa/65e4faf9e8624b7c4c787e0783df15d6.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/c%C3%B2n_l%E1%BA%A1i_n%E1%BB%97i_c%C3%B4_%C4%91%C6%A1n.mp3',
		oga:'#',
		title:'còn lại nỗi cô đơn',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/cu%E1%BB%99c_ch%C6%A1i_v%C3%B4_ngh%C4%A9a.mp3',
		oga:'#',
		title:'cuộc chơi vô nghĩa',
		artist:'Kelly Chen',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:09',
		cover:'https://i.pinimg.com/originals/c5/e6/93/c5e693bb265b90eebe8e8ba799e5e133.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/cu%E1%BB%99c_t%C3%ACnh_v%E1%BA%A1n_d%E1%BA%B7m.mp3',
		oga:'#',
		title:'cuộc tình vạn dặm',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:48',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/d%C3%A1ng_em.mp3',
		oga:'#',
		title:'dáng em',
		artist:'Terry Lin',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:23',
		cover:'https://i.pinimg.com/originals/47/ce/95/47ce95688bda81c74ff264791392f6ce.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/d%C3%B9_c%C3%B3_l%C3%A0_ng%C6%B0%E1%BB%9Di_t%C3%ACnh.mp3',
		oga:'#',
		title:'dù có là người tình',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:07',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/%C4%91ao_ki%E1%BA%BFm_nh%C6%B0_m%E1%BB%99ng.mp3',
		oga:'#',
		title:'đao kiếm như mộng',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:01',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/%C4%91au-th%C6%B0%C6%A1ng-v%C3%AC-em.mp3',
		oga:'#',
		title:'đau thương chỉ vì em',
		artist:'Eric Moo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/c6/1a/9f/c61a9f2afb7ac4d85724dfc4b4efe00b.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/em_c%C3%B3_y%C3%AAu_anh_kh%C3%B4ng.mp3',
		oga:'#',
		title:'em có yêu anh không',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:49',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thi%C3%AAn_long_b%C3%A1t_b%E1%BB%99.mp3',
		oga:'#',
		title:'giang sơn tươi đẹp',
		artist:'Wallace Chung',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'01:59',
		cover:'https://i.pinimg.com/originals/ab/8f/f8/ab8ff8c69f77d8e05bb37311f415bef7.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thanh_ki%E1%BA%BFm_%C4%91%E1%BB%93_long.mp3',
		oga:'#',
		title:'gió mây chuyển sắc',
		artist:'Lawrence Ng',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:18',
		cover:'https://i.pinimg.com/originals/61/e2/75/61e275d76bdbff8d364d3b0c404430a2.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/hao-han-truong-kiet.mp3',
		oga:'#',
		title:'hảo hán',
		artist:'Jason Zhang',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:52',
		cover:'https://i.pinimg.com/originals/e5/ad/d0/e5add0e8e65a7a4cd4b3f28da18d11b8.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/hoa_b%E1%BA%B1ng_l%C4%83ng.mp3',
		oga:'#',
		title:'hoa bằng lăng',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:28',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/khi_n%C3%A0o_em_m%E1%BB%9Bi_bi%E1%BA%BFt.mp3',
		oga:'#',
		title:'khi nào em mới biết',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:39',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/kh%C3%BAc_nh%E1%BA%A1c_bu%E1%BB%93n.mp3',
		oga:'#',
		title:'khúc nhạc buồn',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:22',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ki%E1%BA%BFp_ve_s%E1%BA%A7u.mp3',
		oga:'#',
		title:'kiếp ve sầu',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:40',
		cover:'https://i.pinimg.com/originals/25/36/0a/25360a7b92f4f9d20da9879ea1c9970a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/kinh_kh%C3%B3_ni%E1%BB%87m.mp3',
		oga:'#',
		title:'kinh khó niệm',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:46',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/loves_first_experiment.mp3',
		oga:'#',
		title:'love first experiment',
		artist:'Chang Chen-yue',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:02',
		cover:'https://i.pinimg.com/originals/e9/57/42/e95742d1d88da5e2c4827fa7396e109e.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%81m_l%C3%B2ng.mp3',
		oga:'#',
		title:'mềm lòng',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'05:54',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thi%C3%AAn-nhai-minh-nguy%E1%BB%87t.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa it vũng tàu badboy: minh nguyệt">minh nguyệt</a>',
		artist:'it vũng tàu badboy',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:34',
		cover:'https://i.pinimg.com/originals/8f/6c/39/8f6c39ddb80e3b2d911b24861382775a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%8Bt_m%C3%B9_n%E1%BB%97i_nh%E1%BB%9B.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa diệp tịnh văn: mịt mù nỗi nhớ">mịt mù nỗi nhớ</a>',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:52',
		cover:'https://i.pinimg.com/originals/5c/fe/03/5cfe0318bde3b968720a7026e6c25959.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/moons_heart.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa diệp tịnh văn: moons heart">moons heart</a>',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:28',
		cover:'https://i.pinimg.com/originals/5c/fe/03/5cfe0318bde3b968720a7026e6c25959.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%E1%BB%99ng_%C4%91%E1%BA%B9p_ng%C3%A0y_x%C6%B0a.mp3',
		oga:'#',
		title:'mộng đẹp ngày xưa',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'02:40',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/m%C6%B0a_tr%C3%AAn_cu%E1%BB%99c_t%C3%ACnh.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa tôn lộ: mưa trên cuộc tình">mưa trên cuộc tình</a>',
		artist:'Sun Lu',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:11',
		cover:'https://i.pinimg.com/originals/24/45/0b/24450b943b11b41bfa69c1e6dc4e5c72.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/never_meant_to_hurt_you.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa alex to: never meant to hurt you">never meant to hurt you</a>',
		artist:'Alex To',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:55',
		cover:'https://i.pinimg.com/originals/dd/10/95/dd109500809ca4f9e18486ab3e5135fb.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ng%C3%A0n_5_t%C6%B0%C6%A1ng_ph%C3%B9ng.mp3',
		oga:'#',
		title:'ngàn năm tương phùng',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:08',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/nh%E1%BB%AFng_l%E1%BB%9Di_d%E1%BB%91i_gian.mp3',
		oga:'#',
		title:'những lời dối gian',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'02:34',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/n%E1%BB%A5_h%C3%B4n_bi%E1%BB%87t_ly.mp3',
		oga:'#',
		title:'nụ hôn biệt ly',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'05:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/n%E1%BB%A5_h%C3%B4n_v%C3%A0_n%C6%B0%E1%BB%9Bc_m%E1%BA%AFt.mp3',
		oga:'#',
		title:'nụ hôn và nước mắt',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'05:13',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/heart_broken_in_the_past.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa diệp tịnh văn: nụ hồng mong manh">nụ hồng mong manh</a>',
		artist:'Sally Yeh',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:41',
		cover:'https://i.pinimg.com/originals/5c/fe/03/5cfe0318bde3b968720a7026e6c25959.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/para_para_sakura.mp3',
		oga:'#',
		title:'para para sakura',
		artist:'Aaron Kwok',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/c5/f5/35/c5f53501c9543d9f8e87e996d6b1889d.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/phong_3_t%C3%ACnh_%C4%91%E1%BB%9Di.mp3',
		oga:'#',
		title:'phong ba tình đời',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:38',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/remember.mp3',
		oga:'#',
		title:'remember',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:10',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/sai_l%E1%BA%A7m_v%E1%BA%ABn_l%C3%A0_anh.mp3',
		oga:'#',
		title:'sai lầm vẫn là anh',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:04',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%A2n_s%E1%BB%9F_l%C6%B0u_h%C6%B0%C6%A1ng.mp3',
		oga:'#',
		title:'sở lưu hương',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/sunset.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa it vũng tàu badboy: sunset">sunset</a>',
		artist:'it vũng tàu badboy',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:34',
		cover:'https://i.pinimg.com/originals/8f/6c/39/8f6c39ddb80e3b2d911b24861382775a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/th%E1%BA%A7m_g%E1%BB%8Di_t%C3%AAn_em.mp3',
		oga:'#',
		title:'thầm gọi tên em',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'08:31',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/th%E1%BA%A7n_%C4%91i%C3%AAu_95.mp3',
		oga:'#',
		title:'thiên hạ hữu tình',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thi%C3%AAn_nhai.mp3',
		oga:'#',
		title:'<a rel="tag" title="Top nhạc hoa it vũng tàu badboy: thiên nhai">thiên nhai</a>',
		artist:'it vũng tàu badboy',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:34',
		cover:'https://i.pinimg.com/originals/8f/6c/39/8f6c39ddb80e3b2d911b24861382775a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/thinking_is_useless.mp3',
		oga:'#',
		title:'thinking is useless',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:13',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ti%E1%BB%85n_b%E1%BA%A1n_l%C3%AAn_%C4%91%C6%B0%E1%BB%9Dng.mp3',
		oga:'#',
		title:'tiễn bạn lên đường',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:19',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ti%E1%BA%BFng_s%C3%A1o_phi%C3%AAu_b%E1%BB%93ng.mp3',
		oga:'#',
		title:'tiếng sáo phiêu bồng',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:19',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/ti%E1%BA%BFu_ng%E1%BA%A1o_giang_h%E1%BB%93.mp3',
		oga:'#',
		title:'tiếu ngạo giang hồ',
		artist:'Richie Ren',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:30',
		cover:'https://i.pinimg.com/originals/1e/fd/4b/1efd4b7d14dad2416209e20120a1360a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_%C4%91%E1%BA%A7u_ch%C6%B0a_ngu%C3%B4i.mp3',
		oga:'#',
		title:'tình đầu chưa nguôi',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_%C4%91%C6%A1n_c%C3%B4i.mp3',
		oga:'#',
		title:'tình đơn côi',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:25',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/heart_wants_you_to_hear.mp3',
		oga:'#',
		title:'tình đơn phương',
		artist:'Samuel Tai',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:30',
		cover:'https://i.pinimg.com/originals/25/36/0a/25360a7b92f4f9d20da9879ea1c9970a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_nh%E1%BA%A1t_phai.mp3',
		oga:'#',
		title:'tình nhạt phai',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_nh%C6%B0_gi%C3%B3_nh%C6%B0_m%C6%B0a.mp3',
		oga:'#',
		title:'tình như gió mưa',
		artist:'Timi Zhuo',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:32',
		cover:'https://i.pinimg.com/originals/8f/24/11/8f24112ea8cfb4ed63528cfe86b3af49.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%ACnh_s%C3%A2u_bi%E1%BB%83n_c%C3%A0ng_s%C3%A2u.mp3',
		oga:'#',
		title:'tình sâu biển sâu',
		artist:'Gigi Lai',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:53',
		cover:'https://i.pinimg.com/originals/f1/73/80/f173806c55ec20b84fe30cb483cccb24.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C3%B4i_kh%C3%B4ng_tin.mp3',
		oga:'#',
		title:'tôi không tin',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'03:23',
		cover:'https://i.pinimg.com/originals/c5/00/ea/c500ea03b89235352a33ea295d43a6b3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/tr%E1%BB%9F_l%E1%BA%A1i_ph%E1%BB%91_c%C5%A9.mp3',
		oga:'#',
		title:'trở lại phố cũ',
		artist:'Leon Lai',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'05:00',
		cover:'https://i.pinimg.com/originals/6e/0f/be/6e0fbee64b0fffb69661f9ab87816aa3.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/t%C6%B0%C6%A1ng_t%C6%B0_trong_m%C6%B0a.mp3',
		oga:'#',
		title:'tương tư trong mưa',
		artist:'Jacky Cheung',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:03',
		cover:'https://i.pinimg.com/originals/8f/64/41/8f644187eeaf779543a2489abae6f681.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/tuy%E1%BA%BFt_s%C6%A1n_phi_h%E1%BB%93.mp3',
		oga:'#',
		title:'tuyết sơn phi hồ',
		artist:'itvtbadboy',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:34',
		cover:'https://i.pinimg.com/originals/8f/6c/39/8f6c39ddb80e3b2d911b24861382775a.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/v%E1%BA%A7ng_tr%C4%83ng_kh%C3%B3c.mp3',
		oga:'#',
		title:'vầng trăng khóc',
		artist:'Wakin Chau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'05:22',
		cover:'https://i.pinimg.com/originals/bd/96/9a/bd969a3c4238af327a131960d4b7e8da.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/v%E1%BA%BFt_th%C6%B0%C6%A1ng_l%C3%B2ng.mp3',
		oga:'#',
		title:'vết thương lòng',
		artist:'Andy Lau',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:22',
		cover:'https://i.pinimg.com/originals/df/0d/fc/df0dfc2c020ac37d293b7b9d765de1ed.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/chinese/v%C3%AC_1_ng%C6%B0%E1%BB%9Di_ra_%C4%91i.mp3',
		oga:'#',
		title:'vì 1 người ra đi',
		artist:'Adam Cheng',
		rating:5,
		buy:'https://www.itvtbadboy.io.vn/itvtbadboy/music/nhac-hoa-chon-loc-bat-hu.html',
		price:'0',
		duration:'04:27',
		cover:'https://i.pinimg.com/originals/c5/00/ea/c500ea03b89235352a33ea295d43a6b3.jpg'
	}
];
