var myPlaylist = [
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-caravan-of-life.mp3',
		oga:'#',
		title:'caravan of life',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-caravan-of-life.mp3',
		price:'0',
		duration:'04:13',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-co-don-mot-vi-sao.mp3',
		oga:'#',
		title:'cô đơn 1 vì sao',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-co-don-mot-vi-sao.mp3',
		price:'0',
		duration:'05:36',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-enternal-flame.mp3',
		oga:'#',
		title:'eternal flame',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-enternal-flame.mp3',
		price:'0',
		duration:'03:24',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-hoa-bang-lang.mp3',
		oga:'#',
		title:'hoa bằng lăng',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-hoa-bang-lang.mp3',
		price:'0',
		duration:'04:50',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-lang-le-mua-dong.mp3',
		oga:'#',
		title:'lặng lẽ mùa đông',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-lang-le-mua-dong.mp3',
		price:'0',
		duration:'04:28',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-moi-mon.mp3',
		oga:'#',
		title:'mỏi mòn',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-moi-mon.mp3',
		price:'0',
		duration:'04:56',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-mot-kiep-phong-ba.mp3',
		oga:'#',
		title:'1 kiếp phong ba',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-mot-kiep-phong-ba.mp3',
		price:'0',
		duration:'04:02',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nguyet-tinh.mp3',
		oga:'#',
		title:'nguyệt tình',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nguyet-tinh.mp3',
		price:'0',
		duration:'03:10',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nho-em-nhieu-hon.mp3',
		oga:'#',
		title:'nhớ em nhiều hơn',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nho-em-nhieu-hon.mp3',
		price:'0',
		duration:'03:24',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nu-hon-va-nuoc-mat.mp3',
		oga:'#',
		title:'nụ hôn và nước mắt',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nu-hon-va-nuoc-mat.mp3',
		price:'0',
		duration:'05:10',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nu-hong-mong-manh.mp3',
		oga:'#',
		title:'nụ hồng mong manh',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-nu-hong-mong-manh.mp3',
		price:'0',
		duration:'04:29',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-take-me-to-your-heart.mp3',
		oga:'#',
		title:'take me to your heart',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-take-me-to-your-heart.mp3',
		price:'0',
		duration:'05:26',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-than-thoai.mp3',
		oga:'#',
		title:'thần thoại',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-than-thoai.mp3',
		price:'0',
		duration:'04:50',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-thien-sinh-nhai.mp3',
		oga:'#',
		title:'thiên sinh nhai',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-thien-sinh-nhai.mp3',
		price:'0',
		duration:'02:27',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-thu-muon.mp3',
		oga:'#',
		title:'thu muộn',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-thu-muon.mp3',
		price:'0',
		duration:'03:44',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-tieu-ngao-giang-ho.mp3',
		oga:'#',
		title:'tiếu ngạo giang hồ',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-tieu-ngao-giang-ho.mp3',
		price:'0',
		duration:'03:14',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-tinh-xua-nghia-cu-1.mp3',
		oga:'#',
		title:'tình xưa nghĩa cũ 1',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-tinh-xua-nghia-cu-1.mp3',
		price:'0',
		duration:'04:15',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-tinh-xua-nghia-cu-2.mp3',
		oga:'#',
		title:'tình xưa nghĩa cũ 2',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-tinh-xua-nghia-cu-2.mp3',
		price:'0',
		duration:'03:51',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-toi-se-khong-yeu.mp3',
		oga:'#',
		title:'tôi sẽ không yêu',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-toi-se-khong-yeu.mp3',
		price:'0',
		duration:'04:04',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-vi-anh-yeu-em.mp3',
		oga:'#',
		title:'vì anh yêu em',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-vi-anh-yeu-em.mp3',
		price:'0',
		duration:'04:35',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-yeu-mot-nguoi.mp3',
		oga:'#',
		title:'yêu 1 người',
		artist:'sáo trúc',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/flu-yeu-mot-nguoi.mp3',
		price:'0',
		duration:'04:04',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-999-doa-hong.mp3',
		oga:'#',
		title:'999 đóa hồng',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-999-doa-hong.mp3',
		price:'0',
		duration:'04:18',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-ao-mong-tinh-yeu.mp3',
		oga:'#',
		title:'ảo mộng tình yêu',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-ao-mong-tinh-yeu.mp3',
		price:'0',
		duration:'04:14',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-chiec-la-mua-dong.mp3',
		oga:'#',
		title:'chiếc lá mùa đông',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-chiec-la-mua-dong.mp3',
		price:'0',
		duration:'04:03',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-con-lai-nho-thuong.mp3',
		oga:'#',
		title:'còn lại nhớ thương',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-con-lai-nho-thuong.mp3',
		price:'0',
		duration:'03:55',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-doi-buom-bay-luon.mp3',
		oga:'#',
		title:'đôi bướm bay lượn',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-doi-buom-bay-luon.mp3',
		price:'0',
		duration:'03:53',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-duong-ve-hai-thon.mp3',
		oga:'#',
		title:'đường về 2 thôn',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-duong-ve-hai-thon.mp3',
		price:'0',
		duration:'03:53',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-endless-love.mp3',
		oga:'#',
		title:'endless love',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-endless-love.mp3',
		price:'0',
		duration:'02:31',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-giac-mo-mot-cuoc-tinh.mp3',
		oga:'#',
		title:'giấc mơ 1 cuộc tình',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-giac-mo-mot-cuoc-tinh.mp3',
		price:'0',
		duration:'04:00',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-khong-ten.mp3',
		oga:'#',
		title:'không tên',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-khong-ten.mp3',
		price:'0',
		duration:'02:38',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-loi-lam-da-qua.mp3',
		oga:'#',
		title:'lỗi lầm đã qua',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-loi-lam-da-qua.mp3',
		price:'0',
		duration:'04:57',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-mong-uyen-uong.mp3',
		oga:'#',
		title:'mộng uyên ương hồ điệp',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-mong-uyen-uong.mp3',
		price:'0',
		duration:'03:56',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-mot-nhanh-mai.mp3',
		oga:'#',
		title:'1 nhành mai',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-mot-nhanh-mai.mp3',
		price:'0',
		duration:'03:35',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-tieng-sao-phieu-bong.mp3',
		oga:'#',
		title:'tiếng sáo phiêu bồng',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-tieng-sao-phieu-bong.mp3',
		price:'0',
		duration:'02:31',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-tomorrow-will-come.mp3',
		oga:'#',
		title:'tomorrow will come',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-tomorrow-will-come.mp3',
		price:'0',
		duration:'05:04',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	},
	{
		mp3:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-tuong-tu-trong-mua.mp3',
		oga:'#',
		title:'tương tư trong mưa',
		artist:'đàn tranh',
		rating:5,
		buy:'https://storage.googleapis.com/khuong-itvtbadboy-8383.appspot.com/concert/guz-tuong-tu-trong-mua.mp3',
		price:'0',
		duration:'04:06',
		cover:'https://i.pinimg.com/originals/c5/2f/3e/c52f3ee68a4a7cc9c52bbd7cb30fd558.jpg'
	}
];
